title: Supulim blog
description: 끄적끄적

url:   https://supulim.github.io
image: /images/logo.png

show_downloads: false
future:         true
# timezone:       Asia/Seoul

cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

permalink: /:categories/:title

# social
author: Teddy Lee
disqus_shortname:   teddylee777
google_analytics:   UA-111508093-1

repository: teddylee777/teddylee777.github.io

highlighter: rouge
markdown:    kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false

# root_dir: http://localhost:4000
category_dir: categories/
tag_dir: tag/
categories: [android, aws, data_science, git, jekyll, linux, machine-learning, python, pytorch, review, synology, thoughts]

paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

